### PR TITLE
[CodeCamp2023-646] MMagic新config体验与适配 Textual Inversion

### PR DESCRIPTION
**Pull request by AllYoung**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Add new configs of Textual Inversion

The output of config_validate.py:
config_validate

In addition, I also compared the configuration files obtained by running the training dump on the new and old configs, and found that they are only different in the "type" field. The new configs have full information. Some screenshots are as follows:
config file in workdir

## Checklist

Submitting this pull request means that,

**Before PR**:

- [x] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmagic/blob/main/.github/CONTRIBUTING.md) to create this PR.
- [x] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmagic/blob/main/.github/CONTRIBUTING.md) are used to fix the potential lint issues.
- [x] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] New functionalities are covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [x] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [x] If the modification has potential influence on downstream or other related projects, this PR should be tested with some of those projects.
- [x] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by AllYoung** [comment]
The model training log is as follows.

train log

**Review by LeoXing1996 — CHANGES_REQUESTED** [review]
Hey @AllYoung , thanks for your contribution!
Can you provide a screenshot of an automatically saved image during the training process?
BTW, the lint error should be fixed as well. You can install `pre-commit` hook via the following command
```bash
pip install pre-commit
pre-commit install
```
Then the lint errors will be automatically detected and fixed when you create a commit.

**Comment by AllYoung** [comment]
I am not entirely certain, but there were no automatically saved images during the model training process.

The configuration files obtained by running the training dump on the new and old configs is compared , and found that they are only different in the "type" field. The screenshots has been uploaded

**Comment by AllYoung** [comment]
configs/textual_inversion/textual_inversion.py:4:5: F403 'from .._base_.gen_default_runtime import *' used; unable to detect undefined names

The lint errors seems to be a common issue, and I am unsure how to resolve it. I made the modifications following the instructions provided in the official tutorial. If possible, could you please provide some guidance?

**Review by liuwenran — COMMENTED** [review]
new config should be added to mmagic/mmagic/configs.
please see  'https://github.com/open-mmlab/mmagic/tree/main/mmagic/configs/biggan'.

**Comment by LeoXing1996** [comment]
> configs/textual_inversion/textual_inversion.py:4:5: F403 'from .._base_.gen_default_runtime import *' used; unable to detect undefined names
> 
> The lint errors seems to be a common issue, and I am unsure how to resolve it. I made the modifications following the instructions provided in the official tutorial. If possible, could you please provide some guidance?

@AllYoung. As [liuwenran](https://github.com/liuwenran) mentioned, you should move your config to `https://github.com/open-mmlab/mmagic/tree/main/mmagic/configs/textual_inversion/textual_inversion.py`, then error caused by `F403`will disappear.

**Pull request closed without merging**
