### PR TITLE
[CodeCamp2023-643] Add new configs of BigGAN

### PR DESCRIPTION
**Pull request by limafang**
Adapting New Version of config Adapting  BigGAN Algorithm, based on open-mmlab/OpenMMLabCamp#643

## Motivation

MMEngine has introduced a novel configuration mechanism, utilizing which we will perform configuration file adaptation.

## Modification

* Add 2 config python files in mmagic/configs/_base_/datasets/
* Add 6 config python files in mmagic/configs/biggan/
* Add 1 config python files inmmagic/configs/_base_/models/biggan/  

The output of `config_validate.py`:
  
The output of `demo.py`:

## Checklist

**Before PR**:

- [x] Pre-commit or other linting tools are used to fix the potential lint issues.
- [x] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [x] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [x] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [x] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by LeoXing1996** [comment]
Hey @limafang, thanks for your contribution. Could you please also upload the generated results to ensure correctness of configs?

**Comment by limafang** [comment]
@LeoXing1996 do you mean this picture?
image

**Review by LeoXing1996 — CHANGES_REQUESTED** [review]
Nice work, I only have one small modification requests. 
Since PR #2007  is merged, you can remove those comments to skip flake8 checking.

**Comment by limafang** [comment]
ok i will remove them

**Comment by limafang** [comment]
@LeoXing1996 now i remove them, can you check again?

**Review by LeoXing1996 — APPROVED** [review]
LGTM!

**Pull request merged**
