### PR TITLE
[Feature] Support Style-Based Global Appearance Flow for Virtual Try-On

### PR DESCRIPTION
**Pull request by FerryHuang**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

**Before PR**:

- [ ] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmediting/blob/master/.github/CONTRIBUTING.md) to create this PR.
- [ ] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmediting/blob/master/.github/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] New functionalities are covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with some of those projects.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by LeoXing1996** [comment]
Hey @FerryHuang F, thanks for this great work. Since `MMEdit` has changed it's name to `MMagic`, please update your PR with newest `main` branch and change `mmedit` to `mmagic` in package import.

**Comment by LeoXing1996** [comment]
BTW, may I close PR https://github.com/open-mmlab/mmagic/pull/1781?

**Comment by FerryHuang** [comment]
> BTW, may I close PR #1781?

Sure it's okay to close it~

> Hey @FerryHuang F, thanks for this great work. Since `MMEdit` has changed it's name to `MMagic`, please update your PR with newest `main` branch and change `mmedit` to `mmagic` in package import.

Thanks for your review! I hope that my PR branch has now been successfully updated with the main branch of `MMagic`. However, I am uncertain about how to initialize a new model using its config dict, as was done with the func `init_model` in the previous `mmedit.apis`. Should I utilize an `Inferencer `or do customizing `Inferencer` things?

**Comment by LeoXing1996** [comment]
@FerryHuang You can still use `init_model` function by 
```python
from mmagic.apis.inferencers.inference_functions import init_model
```

**Review by LeoXing1996 — APPROVED** [review]

**Pull request merged**
