### PR TITLE
[CodeCamp2023-648]MMagic 新 config 体验与适配 GuidedDiffusion

### PR DESCRIPTION
**Pull request by ooooo-create**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation
add new config for mmagic/guided_diffusion
output of the `config_validate.py` is `True`
屏幕截图 2023-08-29 190418

output of  Infer Instructions
屏幕截图 2023-08-23 164531
the output inTest Instructions `python tools/test.py mmagic/configs/guided_diffusion/adm_ddim250_8xb32_imagenet_64x64.py https://download.openmmlab.com/mmgen/guided_diffusion/adm-u-cvt-rgb_8xb32_imagenet-64x64-7ff0080b.pth`
屏幕截图 2023-08-29 190537
it's show the`label` in  `sample_kwargs` is none（in `adm.py`）,  so i # it,actually ,the config isn't have `label` and ouput is success！
屏幕截图 2023-08-29 191107

屏幕截图 2023-08-29 191243

## Modification

add `mmagic/configs/`

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

Submitting this pull request means that,

**Before PR**:

- [x] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmagic/blob/main/.github/CONTRIBUTING.md) to create this PR.
- [x] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmagic/blob/main/.github/CONTRIBUTING.md) are used to fix the potential lint issues.
- [x] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] New functionalities are covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [x] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [x] If the modification has potential influence on downstream or other related projects, this PR should be tested with some of those projects.
- [x] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by ooooo-create** [comment]
@LeoXing1996 may be it can be reviewed,I just updated it😍

**Review by LeoXing1996 — CHANGES_REQUESTED** [review]
Nice work, I only have one small modification requests.
Since PR https://github.com/open-mmlab/mmagic/pull/2007 is merged, you can remove those comments to skip flake8 checking.

**Comment by ooooo-create** [comment]
> Nice work, I only have one small modification requests. Since PR #2007 is merged, you can remove those comments to skip flake8 checking.

done

**Review by LeoXing1996 — APPROVED** [review]
LGTM

**Pull request merged**
