### PR TITLE
[Doc] add zh-cn intall doc in get_started

### PR DESCRIPTION
**Pull request by wyyang23**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Community tasks ID 163, Translation and improvement of docs/en/get_started/install.md.

## Modification

Translating the install.md in the docs/en/get_started folder and add to docs/zh_cn/get_started folder.

## BC-breaking (Optional)

the modification doesn't introduce changes that break the backward-compatibility of the downstream repositories.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

**Before PR**:

- [x] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmagic/blob/main/.github/CONTRIBUTING.md) to create this PR.
- [x] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmagic/blob/main/.github/CONTRIBUTING.md) are used to fix the potential lint issues.
- [x] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] New functionalities are covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [x] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with some of those projects.
- [x] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by Z-Fran** [comment]
Please run this to fix link error:
```
pip install pre-commit
pre-commit install
pre-commit run --all-files
```

**Comment by wyyang23** [comment]
thanks, I have passed pre-commit.

**Comment by wyyang23** [comment]
> Please run this to fix link error:
> 
> ```
> pip install pre-commit
> pre-commit install
> pre-commit run --all-files
> ```

**Comment by wyyang23** [comment]
why read the Docs build failed?

**Review by Z-Fran — APPROVED** [review]

**Pull request merged**
