### PR TITLE
Translate "How to prepare your own datasets“

### PR DESCRIPTION
**Pull request by zhjunqin**
## Motivation

Translate "How to prepare your own datasets“

## Modification

Translate "How to prepare your own datasets“

## BC-breaking (Optional)

N/A

## Use cases (Optional)

N/A

### CODE REVIEW

**Comment by zengyh1900** [comment]
Hi @zhjunqin ,  thanks for your contribution!
I found you denote this pull request as 'WIP(working in progress)'. Is this pull request ready for reviewing?

**Comment by zhjunqin** [comment]
> Hi @zhjunqin , thanks for your contribution! I found you denote this pull request as 'WIP(working in progress)'. Is this pull request ready for reviewing now?

Please help review, thanks.

**Review by zengyh1900 — APPROVED** [review]
lgtm. Thanks for your contribution!

**Comment by OpenMMLab-Assistant-004** [comment]
Hi @zhjunqin,

We'd like to express our appreciation for your valuable contributions to the mmagic. Your efforts have significantly aided in enhancing the project's quality.
It is our pleasure to invite you to join our community thorugh Discord_Special Interest Group (SIG) channel. This is a great place to share your experiences, discuss ideas, and connect with other like-minded people. To become a part of the SIG channel, send a message to the moderator, OpenMMLab, briefly introduce yourself and mention your open-source contributions in the #introductions channel. Our team will gladly facilitate your entry. We eagerly await your presence. Please follow this link to join us: ​https://discord.gg/UjgXkPWNqA.

If you're on WeChat, we'd also love for you to join our community there. Just add our assistant using the WeChat ID: openmmlabwx. When sending the friend request, remember to include the remark "mmsig + Github ID".

Thanks again for your awesome contribution, and we're excited to have you as part of our community!

**Pull request merged**
